/*
 * MyHwProj
 *
 * REST api for MyHwProj
 *
 * API version: 1.0.0
 * Contact: myhwproj@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"github.com/spf13/viper"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"log"
	"net/http"

	myhwproj "github.com/GIT_USER_ID/GIT_REPO_ID/internal"
)

func connectToDB() (db *gorm.DB, err error) {
	vp := viper.New()
	vp.SetConfigName("db_config")
	vp.SetConfigType("json")
	vp.AddConfigPath(".")
	if err := vp.ReadInConfig(); err != nil {
		log.Fatal(err)
	}
	host := vp.GetString("host")
	port := vp.GetString("port")
	user := vp.GetString("user")
	password := vp.GetString("password")
	dbname := vp.GetString("dbname")
	timeZone := vp.GetString("timeZone")

	dsn := fmt.Sprintf(
		"host=%s port=%s user=%s password=%s dbname=%s TimeZone=%s sslmode=disable",
		host,
		port,
		user,
		password,
		dbname,
		timeZone,
	)

	db, err = gorm.Open(postgres.Open(dsn), &gorm.Config{})
	if err != nil {
		return
	}

	err = db.AutoMigrate(&myhwproj.Homework{}, &myhwproj.Submission{})
	return
}

func main() {
	log.Printf("Server started")

	db, err := connectToDB()
	if err != nil {
		log.Fatal(err)
	}

	SubmissionDao := myhwproj.NewPostgresSubmissionDao(db)
	HomeworkDao := myhwproj.NewPostgresHomeworkDao(db)

	StudentApiService := myhwproj.NewStudentApiService(SubmissionDao, HomeworkDao)
	StudentApiController := myhwproj.NewStudentApiController(StudentApiService)

	StudentPagesApiService := myhwproj.NewStudentPagesApiService(StudentApiService)
	StudentPagesApiController := myhwproj.NewStudentPagesApiController(StudentPagesApiService)

	TeacherApiService := myhwproj.NewTeacherApiService(SubmissionDao, HomeworkDao)
	TeacherApiController := myhwproj.NewTeacherApiController(TeacherApiService)

	TeacherPagesApiService := myhwproj.NewTeacherPagesApiService(TeacherApiService)
	TeacherPagesApiController := myhwproj.NewTeacherPagesApiController(TeacherPagesApiService)

	router := myhwproj.NewRouter(StudentApiController, StudentPagesApiController, TeacherApiController, TeacherPagesApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
