/*
 * MyHwProj
 *
 * REST api for MyHwProj
 *
 * API version: 1.0.0
 * Contact: myhwproj@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	myhwproj "github.com/GIT_USER_ID/GIT_REPO_ID/internal"
)

func main() {
	log.Printf("Server started")

	StudentApiService := myhwproj.NewStudentApiService()
	StudentApiController := myhwproj.NewStudentApiController(StudentApiService)

	StudentPagesApiService := myhwproj.NewStudentPagesApiService()
	StudentPagesApiController := myhwproj.NewStudentPagesApiController(StudentPagesApiService)

	TeacherApiService := myhwproj.NewTeacherApiService()
	TeacherApiController := myhwproj.NewTeacherApiController(TeacherApiService)

	TeacherPagesApiService := myhwproj.NewTeacherPagesApiService()
	TeacherPagesApiController := myhwproj.NewTeacherPagesApiController(TeacherPagesApiService)

	router := myhwproj.NewRouter(StudentApiController, StudentPagesApiController, TeacherApiController, TeacherPagesApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
