/*
 * MyHwProj
 *
 * REST api for MyHwProj
 *
 * API version: 1.0.0
 * Contact: myhwproj@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package myhwproj

import (
	"context"
	"net/http"
	"errors"
)

// StudentApiService is a service that implements the logic for the StudentApiServicer
// This service should implement the business logic for every endpoint for the StudentApi API.
// Include any external packages or services that will be required by this service.
type StudentApiService struct {
}

// NewStudentApiService creates a default api service
func NewStudentApiService() StudentApiServicer {
	return &StudentApiService{}
}

// AddSubmissionStudent - Add new submission
func (s *StudentApiService) AddSubmissionStudent(ctx context.Context, homeworkId int64, newSubmission NewSubmission) (ImplResponse, error) {
	// TODO - update AddSubmissionStudent with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Submission{}) or use other options such as http.Ok ...
	//return Response(200, Submission{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("AddSubmissionStudent method not implemented")
}

// GetHomeworkByIdStudent - Get homework
func (s *StudentApiService) GetHomeworkByIdStudent(ctx context.Context, homeworkId int64) (ImplResponse, error) {
	// TODO - update GetHomeworkByIdStudent with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Homework{}) or use other options such as http.Ok ...
	//return Response(200, Homework{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetHomeworkByIdStudent method not implemented")
}

// GetHomeworkSubmissionsStudent - Get homework submissions
func (s *StudentApiService) GetHomeworkSubmissionsStudent(ctx context.Context, homeworkId int64, offset int32, limit int32) (ImplResponse, error) {
	// TODO - update GetHomeworkSubmissionsStudent with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Submission{}) or use other options such as http.Ok ...
	//return Response(200, []Submission{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetHomeworkSubmissionsStudent method not implemented")
}

// GetHomeworksStudent - Get homeworks
func (s *StudentApiService) GetHomeworksStudent(ctx context.Context, offset int32, limit int32) (ImplResponse, error) {
	// TODO - update GetHomeworksStudent with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Homework{}) or use other options such as http.Ok ...
	//return Response(200, []Homework{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetHomeworksStudent method not implemented")
}

// GetSubmissionStudent - Get submission
func (s *StudentApiService) GetSubmissionStudent(ctx context.Context, submissionId int64) (ImplResponse, error) {
	// TODO - update GetSubmissionStudent with the required logic for this service method.
	// Add api_student_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Submission{}) or use other options such as http.Ok ...
	//return Response(200, Submission{}), nil

	//TODO: Uncomment the next line to return response Response(400, {}) or use other options such as http.Ok ...
	//return Response(400, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSubmissionStudent method not implemented")
}
