/*
 * MyHwProj
 *
 * REST api for MyHwProj
 *
 * API version: 1.0.0
 * Contact: myhwproj@yandex.ru
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package myhwproj

// ImplResponse defines an error code with the associated body
type ImplResponse[T any] struct {
	Code int
	Body T
}
